apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: <WORKLOAD_CLUSTER_NAME>
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  configuration: |
      terraform {
        backend "s3" {
          bucket   = "<STATE_STORE_BUCKET>"
          key      = "registry/clusters/<WORKLOAD_CLUSTER_NAME>/infrastructure/provider-config/terraform.tfstate"
          region = "<CLOUD_REGION>"
          encrypt = true
        }
        required_providers {
          kubernetes = {
            source = "hashicorp/kubernetes"
            version = ">= 2.23.0, < 3.0.0"
          }
          vault = {
            source = "hashicorp/vault"
            version = ">= 3.19.0, < 4.0.0"
          }
          random = {
            source = "hashicorp/random"
            version = ">= 3.6.2, < 4.0.0"
          }
          aws = {
            source = "hashicorp/aws"
            version = ">= 5.30.0, < 6.0.0"
          }
        }
      }
      provider "aws" {
        region = "<WORKLOAD_CLUSTER_REGION>"
        allowed_account_ids = ["<WORKLOAD_CLUSTER_ACCOUNT_ID>"]
        assume_role_with_web_identity {
          session_name = "kubefirst-pro"
          role_arn = "<WORKLOAD_ASSUME_ROLE>"
          web_identity_token_file = "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"
        }
      }
      provider "aws" {
        alias  = "business_mgmt_region"
        region = "<BUSINESS_MGMT_REGION>"
        allowed_account_ids = ["<BUSINESS_MGMT_AWS_ACCOUNT_ID>"]
        assume_role_with_web_identity {
          session_name = "kubefirst-pro"
          role_arn = "<BUSINESS_MGMT_ASSUME_ROLE>"
          web_identity_token_file = "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"
        }
      }
  pluginCache: false
  credentials:
  - filename: gen-nothing
    source: None
    secretRef:
      namespace: crossplane-system
      name: no-creds
      key: token
  - filename: .git-credentials
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: git-credentials
      key: creds
