apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: actions-runner-metaphor
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  replicas: 1
  template:
    spec:
      repository: <GITHUB_OWNER>/<METAPHOR_REPO_NAME>
      image: summerwind/actions-runner-dind
      serviceAccountName: github-runner
      dockerdWithinRunnerContainer: true
      automountServiceAccountToken: true
