apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.12.1
    helm:
      releaseName: external-dns
      values: |
        image:
          repository: registry.k8s.io/external-dns/external-dns
          tag: "v0.13.2"
        serviceAccount:
          create: true
          name: external-dns
        provider: civo
        sources:
        - ingress
        domainFilters:
        - <DOMAIN_NAME>
        env:
        - name: CIVO_TOKEN
          valueFrom:
            secretKeyRef:
              name: civo-creds
              key: civo-token
    chart: external-dns
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
