apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns
    targetRevision: 1.12.1
    helm:
      releaseName: external-dns
      values: |
        image:
          repository: registry.k8s.io/external-dns/external-dns
          tag: "v0.13.2"
        serviceAccount:
          create: true
          name: external-dns
          annotations:
            eks.amazonaws.com/role-arn: 'arn:aws:iam::<AWS_ACCOUNT_ID>:role/external-dns-<CLUSTER_NAME>'
        sources:
        - ingress
        domainFilters:
          - <DOMAIN_NAME>
        env:
        - name: <EXTERNAL_DNS_PROVIDER_TOKEN_ENV_NAME>
          valueFrom:
            secretKeyRef:
              name: <EXTERNAL_DNS_PROVIDER_SECRET_NAME>
              key: <EXTERNAL_DNS_PROVIDER_SECRET_KEY>
    chart: external-dns
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
