apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '21'
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.20.1
    helm:
      values: |-
        nameOverride: argo
        executor:
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 1024Mi
        server:
          serviceAccount:
            create: true
            name: argo-server
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/argo-<CLUSTER_NAME>
          extraArgs:
          - --auth-mode=client
          - --auth-mode=server
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-staging"
            hosts:
              - argo.<DOMAIN_NAME>
            paths: 
              - /
            pathType: Prefix
            tls:
              - secretName: argo-tls
                hosts:
                  - argo.<DOMAIN_NAME>
        useDefaultArtifactRepo: true
        useStaticCredentials: true
        artifactRepository:
          archiveLogs: false
          s3:
            insecure: false
            bucket: <KUBEFIRST_ARTIFACTS_BUCKET>
            keyFormat: "argo-workflows/artifacts\
              /{{workflow.creationTimestamp.Y}}\
              /{{workflow.creationTimestamp.m}}\
              /{{workflow.creationTimestamp.d}}\
              /{{workflow.uid}}\
              /{{workflow.name}}\
              /{{pod.name}}"
            endpoint: s3.amazonaws.com
            region: <CLOUD_REGION>
            useSDKCreds: true
            encryptionOptions:
              enableEncryption: false
    chart: argo-workflows
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
