apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: <WORKLOAD_CLUSTER_NAME>
  annotations:
    argocd.argoproj.io/sync-wave: "-1" 
spec:
  configuration: |
    terraform {
      backend "s3" {
        bucket   = "<KUBEFIRST_STATE_STORE_BUCKET>"
        key      = "registry/clusters/<WORKLOAD_CLUSTER_NAME>/infrastructure/provider-config/terraform.tfstate"
        endpoint = "ewr1.vultrobjects.com"
        region   = "us-east-1"
        skip_credentials_validation = true
        skip_metadata_api_check     = true
        skip_region_validation      = true
        force_path_style            = true
      }
      required_providers {
        vultr = {
          source  = "vultr/vultr"
          version = "2.23.1"
        }
      }
    }
  pluginCache: false
  credentials:
  - filename: .git-credentials
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: git-credentials
      key: creds
