metaphor-go:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: metaphor-go-production.<AWS_HOSTED_ZONE_NAME>
        paths:
          - /
    tls:
    - secretName: metaphor-go-tls
      hosts:
        - "*.<AWS_HOSTED_ZONE_NAME>"
  vaultMountPoint: kubefirst
  vaultSecretPath: production/metaphor
