apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chartmuseum
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://chartmuseum.github.io/charts
    targetRevision: 3.9.3
    helm:
      values: |-
        serviceAccount:
          create: true
          name: chartmuseum
          annotations:
            eks.amazonaws.com/role-arn: 'arn:aws:iam::<AWS_ACCOUNT_ID>:role/chartmuseum-<CLUSTER_NAME>'
        env:
          open:
            AUTH_ANONYMOUS_GET: true
            AWS_SDK_LOAD_CONFIG: true
            STORAGE: amazon
            STORAGE_AMAZON_BUCKET: <KUBEFIRST_ARTIFACTS_BUCKET>
            STORAGE_AMAZON_PREFIX: kubefirst-charts
            STORAGE_AMAZON_REGION: <CLOUD_REGION>
            DISABLE_API: false
          existingSecret: chartmuseum-secrets
          existingSecretMappings:
            BASIC_AUTH_USER: BASIC_AUTH_USER
            BASIC_AUTH_PASS: BASIC_AUTH_PASS
        ingress:
          enabled: true
          pathType: "Prefix"
          annotations:
            <CERT_MANAGER_ISSUER_ANNOTATION_1>
            <CERT_MANAGER_ISSUER_ANNOTATION_2>
            <CERT_MANAGER_ISSUER_ANNOTATION_3>
            <CERT_MANAGER_ISSUER_ANNOTATION_4>
          hosts:
            - name: chartmuseum.<DOMAIN_NAME>
              path: /
              tls: true
              tlsSecret: chartmuseum-tls
          ingressClassName: nginx
    chart: chartmuseum
  destination: 
    server: https://kubernetes.default.svc
    namespace: chartmuseum
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
