metaphor-frontend:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hosts:
      - host: metaphor-frontend-development.<AWS_HOSTED_ZONE_NAME>
        paths:
          - /
    tls:
    - secretName: metaphor-frontend-tls
      hosts:
        - "*.<AWS_HOSTED_ZONE_NAME>"
