apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "60"
spec:
  project: default
  source:
    repoURL: 'https://runatlantis.github.io/helm-charts'
    chart: atlantis
    targetRevision: 3.19.0
    helm:
      parameters:
        - name: orgWhitelist
          value: <GITOPS_REPO_URL_NO_HTTPS>
      values: |-
        atlantisUrl: http://localhost:4141
        serviceAccount:
          create: true
          mount: true
        resources:
          limits:
            cpu: 400m
            memory: 1Gi
          requests:
            cpu: 400m
            memory: 512Mi
        loadEnvFromSecrets:
          - atlantis-secrets
        repoConfig: |
          ---
          repos:
          - id: <GITOPS_REPO_URL_NO_HTTPS>
            workflow: default
            allowed_overrides: [apply_requirements]
            apply_requirements: [mergeable]
  destination:
    server: "https://kubernetes.default.svc"
    namespace: atlantis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
