apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: atlantis
  namespace: atlantis
spec:
  routes:
    - kind: Rule
      match: Host(`atlantis.<DOMAIN_NAME>`)
      services:
        - name: atlantis
          port: 80
  tls:
    secretName: atlantis-tls
