apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: 'https://charts.min.io/'
    targetRevision: 4.0.15
    helm:
      values: |-
        environment:
          MINIO_BROWSER_REDIRECT_URL: https://console.minio.<LOCAL_DNS>
        ingress:
          enabled: true
          annotations:
            ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
          path: /
          hosts:
            - minio.<LOCAL_DNS>
          tls:
            - secretName: minio-tls
              hosts:
                - minio.<LOCAL_DNS>
        consoleIngress:
          enabled: true
          annotations:
            ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
          path: /
          hosts:
            - console.minio.<LOCAL_DNS>
          tls:
            - secretName: minio-tls
              hosts:
                - minio.<LOCAL_DNS>
        replicas: 1
        rootUser: k-ray
        rootPassword: feedkraystars
        persistence:
          enabled: false
        resources:
          requests:
            memory: 500Mi
        gateway:
          replicas: 1
        mode: standalone
        buckets:
        - name: chartmuseum
          policy: none
          purge: true
          versioning: false
          objectlocking: false
        - name: argo-artifacts
          policy: public
          purge: true
          versioning: false
          objectlocking: false
        - name: gitlab-backup
          policy: none
          purge: true
          versioning: false
          objectlocking: false
        - name: kubefirst-state-store
          policy: none
          purge: true
          versioning: false
          objectlocking: false
        - name: vault-backend
          policy: none
          purge: true
          versioning: false
          objectlocking: false
    chart: minio
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
