apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: minio
  namespace: minio
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`minio.<LOCAL_DNS>`)
    services:
    - name: minio
      port: 80
  tls:
    secretName: minio-tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: minio-console
  namespace: minio
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`minio-console.<LOCAL_DNS>`)
    services:
    - name: minio-console
      port: 80
  tls:
    secretName: minio-console-tls
---
# todo: technical debt: https://github.com/kubefirst/kubefirst/issues/941
#apiVersion: traefik.containo.us/v1alpha1
#kind: Middleware
#metadata:
#  name: redirect-to-https
#  namespace: minio
#spec:
#  redirectScheme:
#    scheme: https
#    permanent: true
