metaphor:
  image:
    repository: registry.gitlab.com/<GITLAB_OWNER>/metaphor
  imagePullSecrets:
    - name: metaphor-deploy
  ingress:
    className: nginx
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    hosts:
      - host: metaphor-development.<DOMAIN_NAME>
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: metaphor-tls
        hosts:
          - metaphor-development.<DOMAIN_NAME>
  metaphor:
    host: https://metaphor-development.<DOMAIN_NAME>/api

