metaphor:
  image:
    repository: <CONTAINER_REGISTRY_URL>/metaphor
  ingress:
    className: nginx
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: '<CLUSTER_ISSUER>'
    hosts:
      - host: metaphor-production.<DOMAIN_NAME>
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: metaphor-tls
        hosts:
          - metaphor-production.<DOMAIN_NAME>
  metaphor:
    host: https://metaphor-production.<DOMAIN_NAME>/api
    console: https://kubefirst.<DOMAIN_NAME>
  vaultSecretPath: production/metaphor
