apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '10'
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/crossplane-<CLUSTER_NAME>
  labels:
    app: crossplane-provider-terraform
  name: terraform-config
spec:
  args:
  - -d
  - --poll=2m
  - --max-reconcile-rate=10
  envFrom:
  - secretRef:
      name: crossplane-secrets
