metaphor:
  image:
    repository: <CONTAINER_REGISTRY_URL>/metaphor
  imagePullSecrets:
    - name: metaphor-deploy
  ingress:
    className: nginx
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: 'letsencrypt-prod'
    hosts:
      - host: metaphor-staging.<DOMAIN_NAME>
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: metaphor-tls
        hosts:
          - metaphor-staging.<DOMAIN_NAME>
  metaphor:
    host: https://metaphor-staging.<DOMAIN_NAME>/api
    console: https://kubefirst.<DOMAIN_NAME>
