apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "21"
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.20.1
    helm:
      values: |-
        nameOverride: argo
        server:
          extraArgs:
          - --auth-mode=client
          - --auth-mode=server
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            hosts:
              - argo.<DOMAIN_NAME>
            paths: 
              - /
            pathType: Prefix
            tls:
              - secretName: argo-tls
                hosts:
                  - argo.<DOMAIN_NAME>
        useDefaultArtifactRepo: true
        useStaticCredentials: true
        artifactRepository:
          archiveLogs: false
          s3:
            accessKeySecret:
              name: ci-secrets
              key: accesskey
            secretKeySecret:
              name: ci-secrets
              key: secretkey
            insecure: false
            bucket: <KUBEFIRST_STATE_STORE_BUCKET>
            endpoint: objectstore.<CLOUD_REGION>.civo.com
            region: <CLOUD_REGION>
            useSDKCreds: false
            encryptionOptions:
              enableEncryption: false
    chart: argo-workflows
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
