apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  project: default
  source:
    repoURL: 'https://argoproj.github.io/argo-helm'
    chart: argo-cd
    targetRevision: 4.9.14
    helm:
      values: |-
        server:
          rbacConfig:
            policy.csv: |
              g, admins, role:admin
              g, developers, role:readonly
            policy.default: role:readonly
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"
            hosts:
              - argocd.<AWS_HOSTED_ZONE_NAME>
            paths:
              - /
            pathType: Prefix
            tls:
              - secretName: argocd-server-tls
                hosts: 
                  - argocd.<AWS_HOSTED_ZONE_NAME>
            https: true
          additionalApplications:
          - name: registry
            namespace: argocd
            additionalLabels: {}
            additionalAnnotations: {}
            finalizers:
            - resources-finalizer.argocd.argoproj.io
            project: default
            source:
              repoURL: <FULL_REPO_GITOPS_URL>
              targetRevision: HEAD
              path: registry
            destination:
              server: https://kubernetes.default.svc
              namespace: argocd
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
              syncOptions:
              - CreateNamespace=true
              retry:
                limit: 5
                backoff:
                  duration: 5s
                  maxDuration: 5m0s
                  factor: 2
          config:
            oidc.config: |
              name: Vault
              issuer: https://vault.<AWS_HOSTED_ZONE_NAME>/v1/identity/oidc/provider/kubefirst
              clientID: <ARGOCD_OIDC_CLIENT_ID>
              clientSecret: $argocd-oidc-secret:clientSecret
              requestedScopes: ["openid", "groups", "user", "profile", "email"]
              requestedIDTokenClaims: {"groups": {"essential": true}}
            url: 'https://argocd.<AWS_HOSTED_ZONE_NAME>'        
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
