apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: metaphor-frontend-development-ingress
  namespace: development
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`metaphor-frontend-development.<LOCAL_DNS>`)
    services:
    - name: metaphor-frontend-development
      port: 80
  tls:
    secretName: metaphor-frontend-development-tls
---
# todo: technical debt: https://github.com/kubefirst/kubefirst/issues/941
{{/*apiVersion: traefik.containo.us/v1alpha1*/}}
{{/*kind: Middleware*/}}
{{/*metadata:*/}}
{{/*  name: redirect-to-https*/}}
{{/*  namespace: development*/}}
{{/*spec:*/}}
{{/*  redirectScheme:*/}}
{{/*    scheme: https*/}}
{{/*    permanent: true*/}}
