apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlantis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '60'
spec:
  project: default
  source:
    repoURL: 'https://runatlantis.github.io/helm-charts'
    chart: atlantis
    targetRevision: 4.10.3
    helm:
      values: |-
        statefulSet:
          annotations:
            secret.reloader.stakater.com/reload: "atlantis-secrets"
        atlantisUrl: https://atlantis.<DOMAIN_NAME>
        orgAllowlist: <ATLANTIS_ALLOW_LIST>
        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.middlewares: atlantis-redirect-to-https@kubernetescrd
          path: /
          pathType: Prefix
          host: atlantis.<DOMAIN_NAME>
          tls:
            - secretName: atlantis-tls
              hosts:
                - atlantis.<DOMAIN_NAME>
        serviceAccount:
          create: true
          mount: true
        resources:
          limits:
            cpu: 400m
            memory: 1Gi
          requests:
            cpu: 400m
            memory: 512Mi
        loadEnvFromSecrets:
          - atlantis-secrets
        repoConfig: |
          ---
          repos:
          - id: <ATLANTIS_ALLOW_LIST>
            workflow: default
            allowed_overrides: [apply_requirements]
            apply_requirements: [mergeable]
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: atlantis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
