apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`argocd.<LOCAL_DNS>`)
    services:
    - name: argocd
      port: 80
  tls:
    secretName: argocd-tls
---
# todo: technical debt: https://github.com/kubefirst/kubefirst/issues/941
#apiVersion: traefik.containo.us/v1alpha1
#kind: Middleware
#metadata:
#  name: redirect-to-https
#  namespace: argocd
#spec:
#  redirectScheme:
#    scheme: https
#    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-redirect
  namespace: argocd
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    traefik.ingress.kubernetes.io/router.middlewares: argocd-redirect-to-https@kubernetescrd

spec:
  rules:
    - host: argocd.<LOCAL_DNS>
      http:
        paths:
          - backend:
              service:
                name: argocd-server
                port:
                  number: 80
            path: /
            pathType: Prefix
