metaphor:
  image:
    repository: registry.gitlab.com/<GITLAB_OWNER>/metaphor
  imagePullSecrets:
    - name: metaphor-deploy
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: development-redirect-to-https@kubernetescrd
    className: ''
    hosts:
      - host: metaphor-development.<DOMAIN_NAME>
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: metaphor-development-tls
        hosts:
          - metaphor-development.<DOMAIN_NAME>
  metaphor:
    host: https://metaphor-development.<DOMAIN_NAME>/api
  vaultMountPoint: kubefirst
  vaultSecretPath: development/metaphor
  isLocal: true
