metaphor:
  image:
    repository: registry.gitlab.com/<GITLAB_OWNER>/metaphor
  imagePullSecrets:
    - name: docker-config
  ingress:
    enabled: true
    className: ''
    hosts:
      - host: metaphor-development.<DOMAIN_NAME>
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: metaphor-development-tls
        hosts:
          - metaphor-development.<DOMAIN_NAME>
  metaphor:
    host: https://metaphor-development.<DOMAIN_NAME>/api
    console: https://kubefirst.<DOMAIN_NAME>
  vaultMountPoint: kubefirst
  vaultSecretPath: development/metaphor
  originIssuerIsEnabled: false
