apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: 'https://charts.min.io/'
    targetRevision: 4.0.15
    helm:
      values: |-
        environment:
          MINIO_BROWSER_REDIRECT_URL: https://minio-console.<DOMAIN_NAME>
        ingress:
          enabled: true
          path: /
          hosts:
            - minio.<DOMAIN_NAME>
          tls:
            - secretName: minio-tls
              hosts:
                - minio.<DOMAIN_NAME>
        consoleIngress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.middlewares: minio-redirect-to-https@kubernetescrd
          path: /
          hosts:
            - minio-console.<DOMAIN_NAME>
          tls:
            - secretName: minio-console-tls
              hosts:
                - minio-console.<DOMAIN_NAME>
        replicas: 1
        rootUser: k-ray
        rootPassword: feedkraystars
        persistence:
          enabled: true
          existingClaim: minio-pv-claim
        resources:
          requests:
            memory: 500Mi
        gateway:
          replicas: 1
        mode: standalone
        buckets:
        - name: chartmuseum
          policy: none
          purge: true
          versioning: false
          objectlocking: false
        - name: argo-artifacts
          policy: public
          purge: true
          versioning: false
          objectlocking: false
        - name: gitlab-backup
          policy: none
          purge: true
          versioning: false
          objectlocking: false
        - name: kubefirst-state-store
          policy: none
          purge: true
          versioning: false
          objectlocking: false
        - name: vault-backend
          policy: none
          purge: true
          versioning: false
          objectlocking: false
    chart: minio
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
