apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argo
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: '20'
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argo.<DOMAIN_NAME>`)
      services:
        - name: argo
          port: 80
  tls:
    secretName: argo-tls
