metaphor:
  annotations: |
    linkerd.io/inject: "enabled"
  labels: |
    mirror.linkerd.io/exported: "true"
  image:
    repository: ghcr.io/feedkray-one/metaphor
  imagePullSecrets:
    - name: docker-config
  ingress:
    className: nginx
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: 'letsencrypt-prod'
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
      - host: metaphor-development.<DOMAIN_NAME>
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: metaphor-tls
        hosts:
          - metaphor-development.<DOMAIN_NAME>
  metaphor:
    host: https://metaphor-development.<DOMAIN_NAME>/api
    console: https://kubefirst.<DOMAIN_NAME>

  clusterSecretStoreName: development-vault-kv-secret
  configs:
    configOne: development-cluster-override-one
    configTwo: development-cluster-override-two
