apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-contoller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  project: default
  source:
    repoURL: 'https://actions-runner-controller.github.io/actions-runner-controller'
    targetRevision: 0.20.2
    helm:
      values: |-
        labels: {}

        replicaCount: 1

        webhookPort: 9443
        syncPeriod: 1m
        defaultScaleDownDelay: 10m

        enableLeaderElection: true
        authSecret:
          enabled: true
          name: "controller-manager"

        dockerRegistryMirror: ""
        image:
          repository: "summerwind/actions-runner-controller"
          actionsRunnerRepositoryAndTag: "summerwind/actions-runner:latest"
          dindSidecarRepositoryAndTag: "docker:dind"
          pullPolicy: IfNotPresent
          # The default image-pull secrets name for self-hosted runner container.
          # It's added to spec.ImagePullSecrets of self-hosted runner pods.
          actionsRunnerImagePullSecrets: []

        imagePullSecrets: []
        nameOverride: ""
        fullnameOverride: ""

        runner:
          statusUpdateHook:
            enabled: false

        rbac:
          {}

        serviceAccount:
          create: true
          annotations: {}
          name: ""

        podAnnotations: {}

        podLabels: {}

        podSecurityContext:
          {}

        securityContext:
          {}

        service:
          type: ClusterIP
          port: 443
          annotations: {}

        metrics:
          serviceAnnotations: {}
          serviceMonitor: false
          serviceMonitorLabels: {}
          port: 8443
          proxy:
            enabled: true
            image:
              repository: quay.io/brancz/kube-rbac-proxy
              tag: v0.13.0

        resources:
          {}

        nodeSelector: {}

        tolerations: []

        affinity: {}

        podDisruptionBudget:
          enabled: false

        priorityClassName: ""

        env:
          {}
          # specify additional environment variables for the controller pod.
          # It's possible to specify either key vale pairs e.g.:
          # http_proxy: "proxy.com:8080"
          # https_proxy: "proxy.com:8080"
          # no_proxy: ""

          # or a list of complete environment variable definitions e.g.:
          # - name: GITHUB_APP_INSTALLATION_ID
          #   valueFrom:
          #     secretKeyRef:
          #       key: some_key_in_the_secret
          #       name: some-secret-name
          #       optional: true

        additionalVolumes: []

        additionalVolumeMounts: []

        scope:
          singleNamespace: false
          watchNamespace: ""

        certManagerEnabled: true

        admissionWebHooks:
          {}
    chart: actions-runner-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: github-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Replace=true
      - PruneLast=true
